parameters:
  cl_slack.api_client.class: Treetop1500\Slack\Transport\ApiClient
  cl_slack.mock_api_client.class: Treetop1500\Slack\Test\Transport\MockApiClient
  cl_slack.model_serializer.class: Treetop1500\Slack\Serializer\ModelSerializer
  cl_slack.payload_serializer.class: Treetop1500\Slack\Serializer\PayloadSerializer
  cl_slack.payload_response_serializer.class: Treetop1500\Slack\Serializer\PayloadResponseSerializer

services:
  cl_slack.api_client:
    class: %cl_slack.api_client.class%
    arguments:
      - %cl_slack.api_token%

  cl_slack.mock_api_client:
    class: %cl_slack.mock_api_client.class%

  cl_slack.model_serializer:
    class: %cl_slack.model_serializer.class%

  cl_slack.payload_serializer:
    class: %cl_slack.payload_serializer.class%

  cl_slack.payload_response_serializer:
    class: %cl_slack.payload_response_serializer.class%
